######################################################################
# Automatically generated by qmake (3.0) Wed Dec 14 23:05:20 2016
######################################################################

TEMPLATE = app
TARGET = PairsGame
INCLUDEPATH += .

# Input
SOURCES += \
    card.cpp
QT += widgets

HEADERS += \
    card.h
